// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-KCKm8gO6vz9oN9Nu8bChyAu_G06nqKc',
    appId: '1:231946857135:web:ecac080aa2c308c158025a',
    messagingSenderId: '231946857135',
    projectId: 'store-db-7ba62',
    authDomain: 'store-db-7ba62.firebaseapp.com',
    databaseURL: 'https://store-db-7ba62-default-rtdb.firebaseio.com',
    storageBucket: 'store-db-7ba62.appspot.com',
    measurementId: 'G-48F1F8G53R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGRRkdfoRsq_MYCVz7i-MF_IfIOae6T9s',
    appId: '1:231946857135:android:34fdba8105ce895358025a',
    messagingSenderId: '231946857135',
    projectId: 'store-db-7ba62',
    databaseURL: 'https://store-db-7ba62-default-rtdb.firebaseio.com',
    storageBucket: 'store-db-7ba62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXYJ3i0xE5VhaxoGCxXzR36XQwC4DBss',
    appId: '1:231946857135:ios:f3a8830a233ac79458025a',
    messagingSenderId: '231946857135',
    projectId: 'store-db-7ba62',
    databaseURL: 'https://store-db-7ba62-default-rtdb.firebaseio.com',
    storageBucket: 'store-db-7ba62.appspot.com',
    iosClientId: '231946857135-pgj2g94fk22dj75pf5o26pin8rc7jsh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFXYJ3i0xE5VhaxoGCxXzR36XQwC4DBss',
    appId: '1:231946857135:ios:f3a8830a233ac79458025a',
    messagingSenderId: '231946857135',
    projectId: 'store-db-7ba62',
    databaseURL: 'https://store-db-7ba62-default-rtdb.firebaseio.com',
    storageBucket: 'store-db-7ba62.appspot.com',
    iosClientId: '231946857135-pgj2g94fk22dj75pf5o26pin8rc7jsh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
